name: py38base
on:
  push:
    tags:
      - 'base_v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta_base_common_py38
        uses: docker/metadata-action@v4
        with:
          images: |
            tencentailab/hok_env
          flavor: |
            prefix=base_
            latest=false
          tags: |
            type=sha,prefix=base_common_py38_
            type=raw,value={{tag}},prefix=base_common_py38_
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_base_common_py38.outputs.tags }}
          labels: ${{ steps.meta_base_common_py38.outputs.labels }}
          file: dockerfile/dockerfile.base
          cache-from: type=registry,ref=tencentailab/hok_env:base_common_py38_buildcache
          cache-to: type=registry,ref=tencentailab/hok_env:base_common_py38_buildcache,mode=max
